### ISSUE TITLE
Nethereum Unity 3D Sample and DAO examples compile issues

### ISSUE THREAD

**Issue by 7DEStudios** [Nethereum/Nethereum#311]
Using Nethereum.Unity 2.0.0 and Unity 5.4 getting a issue even with just copying the Unity3DSampleGame directly. It could be that its a older version of Unity but really cant update Unity without changing a lot of the projects code and . With the sample the error:

Assets/DecodeData.cs(51,31): error CS1501: No overload for method `DecodeDTOTypeOutput' takes `2' arguments
Assets/DecodeData.cs(52,43): error CS1061: Type `object' does not contain a definition for `BirthTime' and no extension method `BirthTime' of type `object' could be found (are you missing a using directive or an assembly reference?)
etc...same error for the other variables

My question is there a means to fix it without updating Unity to 2017+ or is that where my problem resides in? Or is it needing to update some files in Nethereum? Or is there something I am doing wrong? Can I create a call that doesnt use web3 to return a value from a smart contract? Its a copy of the sample but I did put Nethereum 2.0.0 in prior. 

I have had no issue using transactions, checking balances, and interacting with contracts with the RPC client except for returning values, I have steered clear of Web3 as of so far except now needing returned call values and reason for using the sample, I have also tried the DAO example and am having a syntax issue with unexpected symbol in Task<List<Proposals>>.

**Comment by juanfranblanco** [comment]
I have not tested it with Unity 5.4. The only problem we should have would be in the UnityEngine versions.
Have you used this version? https://github.com/Nethereum/Unity3dSimpleSample

**Comment by 7DEStudios** [comment]
Ill download it and run that project and see if it resolves it, I figured it might be tied into it really not looking forward to upgrading Unity. Always a pain to fix all the deprecated functions, been working on this project for years and had to do it when i upgraded to 5.4. Ill let you know if it was the issue, 5.4 is definitely outdated so wouldnt suggest working around it if its the issue ,you already have a lot on your plate. Great job by the way, on a very obscure topic you have created the perfect tool.

**Comment by juanfranblanco** [comment]
Thank you, let me know how it goes.

**Comment by juanfranblanco** [comment]
Actually the Nethereum support for .Net 351 was to not force the upgrade. But you seem to be having issues on simple compilation areas, which is rather strange. Theoretically it should only complain about the UnityEngine.

**Comment by 7DEStudios** [comment]
Well upgrading to 2017 fixed the compile issues but Unity started using curl and the hosting server i use for non blockchain storage dont accept it. So i went ahead and went back to Unity 5.4 for the time being. I went ahead and downloaded Nethereum 2.2.1 and it fixed the compile issues I was having. I took the Nethereum.Keystore.dll from 2.0.0 as 2.2.1 didnt have it. Only issue I got after that was ambigious call for the Function output and just dropped the parameter name and that stopped the compile issue.

Now im not sure what part im doing wrong or if dropping the parameter name is causing me issues but here is the code, I'm using pretty much the same thing except using a uint to find the index.

`public IEnumerator GetData(string url)
    {
        string ABI = @"
                    //deleted non releveant ABI
                    {
                        ""constant"": true,
                        ""inputs"": [
                            {
                                ""name"": ""index"",
                                ""type"": ""uint256""
                            }
                        ],
                        ""name"": ""getBuyIndex"",
                        ""outputs"": [
                            {
                                ""name"": ""indexBuy"",
                                ""type"": ""address""
                            }
                        ],
                        ""payable"": false,
                        ""stateMutability"": ""view"",
                        ""type"": ""function""
                    }
                    //deleted non releveant ABI
                    ";

        string buyContractAddress = "0x010101SomeMadeUpAddress01010101010101";

        buycontract = new Contract (null, ABI, buyContractAddress);   
        var getDataCallUnityRequest = new EthCallUnityRequest(url);
        var function = buycontract.GetFunction("getBuyIndex");
        uint buyorderindex = 1; 
        var callInput = function.CreateCallInput(buyorderindex);
        yield return getDataCallUnityRequest.SendRequest(callInput, Nethereum.RPC.Eth.DTOs.BlockParameter.CreateLatest());
        if (getDataCallUnityRequest.Exception == null) {
            var result = getDataCallUnityRequest.Result;
            var thing = new GetDataDTO();
            var output = function.DecodeDTOTypeOutput<GetDataDTO>(thing, result);
            if(output.Address != "0x0"){
                buyorderslist.Add(output.Address);
            }
            if(output.Address == "0x0"){
                buylooped = true;
            }
        } else {
            Debug.Log("Error getting buy index: " + getDataCallUnityRequest.Exception.Message);
        }
    }

    [FunctionOutput]
    public class GetDataDTO
    {
        [Parameter("address", 1)]
        public string Address { get; set; }

    }`

and here is the contract function im using reduced just to use as a quicker example.

`mapping(address => mapping(bool => address))  private dllIndexBuy;

function getBuyIndex(uint index) constant returns (address indexBuy) {        
    address head = 0x0;
    address tempaddr = head;
    address indexedaddr = tempaddr;
    for(uint i = 0; i < index; i++){
        tempaddr = dllIndexBuy[tempaddr][NEXT];
        indexedaddr = tempaddr;
    }
    return (indexedaddr);
}`

I am receiving this error creating the call.

`Error getting buy index: invalid argument 0: json: cannot unmarshal hex string of odd length into Go struct field CallArgs.to of type common.Address`

**Comment by juanfranblanco** [comment]
Closing this for now, although keeping a note for more backward testing compatibility
